const char d[numFrases][18]  PROGMEM = { //primeira sequencia
  "Inezita Barroso",
  "Ronnie Von",
  "Trem da Alegria",
  "A Lagoa Azul",
  "She-Ra",
  "Zizi Possi",
  "Lendas",
  "Ana Carolina",
  "Elton John",
  "As Gostosas",
  "Elis Regina",
  "Mario Bros",
  "Bonnie Tyler",
  "Sinais",
  "Tim Maia",
  "Tchaikovsky",

  //segunda sequencia
  "Avatar",
  "Paula Fernandes",
  "Tom e Jerry",
  "Michael Jackson",
  "The Beatles",
  "Final Space",
  "Game of Thrones",
  "Desafinado",
  "Milton Nascimento",
  "Narcos",
  "Pink Floyd",
  "Madonna",
  "Reconvexo",
  "Joao Gilberto",
  "Roque Santeiro",
  "Adorinan Barbosa",

  "Imagine",
  "Demi Lovato",
  "Lyly Allen",
  "Ney Matogrosso",
  "Queen",
  "Pernalonga",
  "That '70s Show",
  "Frank Sinatra",
  "Billy Paul",
  "Sacrifice",
  "Rugrats",
  "Os Goonies",
  "Ladies Night",
  "Joao Gilberto",
  "Preciosa",
  "Gonzaguinha",

  "Castlevania",
  "Fantastico",
  "Claudia Raia",
  "Clube da Luta",
  "Indiana Jones",
  "Night Fever",
  "Beth Carvalho",
  "Shania Twain",
  "It's Raining Men",
  "Arnold",
  "Ney Matogrosso",
  "Capital Inicial",
  "Emilinha Borba",
  "Baby do Brasil",
  "Nelson Goncalves",
  "Richard Nixon",


  "Dominguinhos",
  "CPM22",
  "Patati Patata",
  "Harry Potter",
  "Bob Dylan",
  "Guilherme Boulos",
  "Carrapicho",
  "Pixote",
  "Brasilia Amarela",
  "One Peace",
  "Tieta",
  "Big Mouth",
  "The Airport",
  "Celly Campelo",
  "Erasmo Carlos",
  "Paulo Amorim",

  //segunda sequencia
  "Kiss",
  "Erasmo Carlos",
  "Maria Rita",
  "Carmem Miranda",
  "Carrossel",
  "You",
  "Elizeth Cardoso",
  "Slash",
  "Chiquititas",
  "Mortal Kombat",
  "Chiquititas",
  "Carinhoso",
  "Dragon Ball",
  "Anaconda",
  "Claymore",
  "Italia"
};
