const char b[numFrases][18] PROGMEM = { //primeira sequencia
  "Kid Abelha",
  "Erasmo Carlos",
  "Mulekada",
  "Uma Linda Mulher",
  "Thundercats",
  "Angelica",
  "Como uma Deusa",
  "Zelia Duncan",
  "Paul McCartney",
  "As Poderosas",
  "Elza Soares",
  "Crash Bandicoot",
  "Ella Fitzgerald",
  "2001",
  "Leo Jaime",
  "Beethoven",

  //Segunda sequencia
  "O Rei Leao",
  "Rita Lee",
  "Bob Esponja",
  "George Michael",
  "ABBA",
  "Futurama",
  "Prison Break",
  "Garota de Ipanema",
  "Flavio Augusto",
  "Black Mirror",
  "Led Zeppelin",
  "Celina Dion",
  "Alegria, Alegria",
  "Edu Lobo",
  "Avenida Brasil",
  "Francisco Alves",

  "Hey Jude",
  "Shania Twain",
  "Lana Del Rey",
  "Sergio Malandro",
  "ABBA",
  "Pica-Pau",
  "Seinfeld",
  "Dean Martin",
  "Ray Charles",
  "Sailing",
  "Garfield",
  "Piratas do Caribe",
  "Run To Me",
  "Edu Lobo",
  "Ghost",
  "Joao do Vale",

  "Super Mario Bros",
  "Bom Dia Brasil",
  "Hebe Camargo",
  "Rocky",
  "Vingadores",
  "Stayin' Alive",
  "Clara Nunes",
  "Cindy Lauper",
  "Car Wash",
  "Chaves",
  "Joao Bosco",
  "Banda Eva",
  "Angela Maria",
  "Celly Campelo",
  "Geraldo Vandre",
  "Ronald Reagan",

  //quinta sequencua
  "Gonzaguinha",
  "Detonautas",
  "Balao Magico",
  "Piratas do Caribe",
  "Guns N' Roses",
  "Cabo Daciolo"  ,
  "Mastruz com Leite",
  "Raca Preta",
  "Pelados em Santos",
  "Pokemon",
  "Alma Gemea",
  "Family Guy",
  "Ghost",
  "Wanderlea",
  "Fabio Junior",
  "Ricardo Boechat",

  //segunda sequencia
  "The Animals",
  "Raul Seixas",
  "Shakira",
  "Elizeth Cardoso",
  "Serafim",
  "La Casa De Papel",
  "Alaide Costa",
  "Nirvana",
  "Carrossel",
  "Rambo",
  "Carinha de Anjo",
  "Porta Aberta",
  "YU GI OH",
  "Tubarao",
  "Berserk",
  "Alemanha"
};
