const char c[numFrases][18] PROGMEM = { //primeira sequencia
  "Gal Costa",
  "Wesley Safadao",
  "Patati Patata",
  "Titanic",
  "He-Man",
  "Xuxa",
  "Alem",
  "Maria Bethania",
  "Billy Joel",
  "As Freneticas",
  "Nara Leao",
  "Bomberman",
  "Cher",
  "Star Wars",
  "Cazuza",
  "Chopin",

  //segunda sequencia
  "Pocahontas",
  "Anitta",
  "Pica Pau",
  "David Bowie",
  "Queen",
  "Family Guy",
  "Breaking Bad",
  "Wave",
  "Lo Borges",
  "Dark",
  "Kiss",
  "Diana Ross",
  "Odara",
  "Toquinho",
  "Rei do Gado",
  "Noel Rosa",

  "Let it Be",
  "Bonnie Tyler",
  "Adele",
  "Cazuza",
  "Bee Gees",
  "Tom e Jerry",
  "Modern Family",
  "Bob Dylan",
  "Prince",
  "Down on Me",
  "Arthur",
  "ET",
  "Mess Around",
  "Toquinho",
  "Rapunzel",
  "Dominguinhos",

  "Bomberman",
  "Jornal Hoje",
  "Dilma Rousseff",
  "Top Gun",
  "Star Wars",
  "I Will Survive",
  "Alcione",
  "Madonna",
  "Hot Stuff",
  "Carrossel",
  "Cazuza",
  "Titas",
  "Isaura Garcia",
  "Wanderlea",
  "Cartola",
  "Bill Clinton",


  "Lobao",
  "Skank",
  "Mulekada",
  "Abracadabra",
  "Pearl Jam",
  "Joao Amoedo",
  "Calcinha Preta",
  "Pique Novo",
  "Seus Cabelos",
  "Dragon ball",
  "Pantanal",
  "Os Simpsons",
  "The Sunshine",
  "Vanusa",
  "Fagner",
  "William Bonner",

  //segunda sequencia
  "Queen",
  "Ronnie Von",
  "Alcione",
  "Pitty",
  "Chiquititas",
  "Elite",
  "Gal Costa",
  "Queen",
  "Malhacao",
  "Tron",
  "Carrossel",
  "A Volta",
  "Naruto",
  "Predador",
  "Evangelion",
  "Espanha"
};
