const char a[numFrases][18] PROGMEM = { //primeira sequencia
  "Rita Lee",
  "Roberto Carlos",
  "Balao Magico",
  "E o vento levou..",
  "Caverna do Dragao",
  "Eliana",
  "O Amor e o Poder",
  "Elizeth Cardoso",
  "John Lennon",
  "As Supremas",
  "Maysa Matarazzo",
  "Donkey Kong",
  "Janis Joplin",
  "Interestelar",
  "Frejat",
  "Mozart",

  //segunda sequencia
  "Frozen",
  "Simone",
  "Popeye",
  "Bob Dylan",
  "Bee Gees",
  "Rick e Morty",
  "Mad Men",
  "Corcovado",
  "Sidney Magal",
  "Dexter",
  "U2",
  "Whitney Houston",
  "Sozinho",
  "Cyro Monteiro",
  "A Favorita",
  "Nelson Goncalves",

  //terceira sequencia
  "Michelle",
  "Nancy Sinatra",
  "Amy Winehouse",
  "Leo Jaime",
  "The Beatles",
  "Scooby Doo",
  "Friends",
  "Rod Stewart",
  "Stevie Wonder",
  "Eternal Flame",
  "Ei Arnold",
  "Peter Pan",
  "Street Life",
  "Cyro Monteiro",
  "O Magico de Oz",
  "Luiz Gonzaga",

  //quarta sequencia
  "Donkey Kong",
  "Jornal Nacional",
  "Dercy Goncalves",
  "Rambo",
  "Jurassic Park",
  "Y.M.C.A.",
  "Elza Soares",
  "Gloria Gaynor",
  "Mamma Mia",
  "Tres eh Demais",
  "Frejat",
  "Radio Taxi",
  "Dalva de Oliveira",
  "Vanusa",
  "Cauby Peixoto",
  "John Kennedy",

  //quinta sequencia
  "Luiz Gonzaga",
  "Nx Zero",
  "Trem da Alegria",
  "Game of Thrones",
  "Ze Ramalho",
  "Jair Bolsonaro",
  "Calypso",
  "Raca Negra",
  "Docinho de Coco",
  "Naruto",
  "A Favorita",
  "American Dad",
  "Titanic",
  "Elba Ramalho",
  "Roberto Carlos",
  "Rodrigo Borcadi",

  //sexta sequencia
  "The Beatles",
  "Roberto Carlos",
  "Elis Regina",
  "Alcione",
  "Carinha de Anjo",
  "Stranger Things",
  "Miucha",
  "King",
  "Rebelde",
  "Karate Kid",
  "Serafim",
  "Cadeira Vazia",
  "Pokemon",
  "Indiana Jones",
  "Hellsing",
  "Franca"
};
