const char pergunta[numFrases][19] PROGMEM = { //primeira sequencia
  "Quem eh a Cantora?",
  "Quem eh o Cantor?",
  "Qual eh o Grupo?",
  "Tema de Que Filme?",
  "Qual o Desenho?",
  "Quem eh a Cantora?",
  "Qual eh a Musica?",
  "Quem eh a Cantora?",
  "Quem eh o Cantor?",
  "Qual eh a Banda?",
  "Quem eh a Cantora?",
  "Tema de Que Jogo?",
  "Quem eh a Cantora?",
  "Tema de Que Filme?",
  "Quem eh o Cantor?",
  "Quem compos?",

  //segunda sequencia
  "Tema de Que Filme?",
  "Quem eh a Cantora?",
  "Qual eh o Desenho?",
  "Quem eh o Cantor?",
  "Qual a Banda?",
  "Qual o Desenho?",
  "Qual a Serie?",
  "Qual eh a Musica?",
  "Quem eh o Cantor?",
  "Qual a Serie?",
  "Qual a Banda?",
  "Quem eh a Cantora?",
  "Qual eh a Musica?",
  "Quem eh o Cantor?",
  "Qual eh a Novela?",
  "Quem eh o Cantor?",

  "Qual eh a Musica?",
  "Quem eh a Cantora?",
  "Qual eh a Cantora?",
  "Quem eh o Cantor?",
  "Qual a Banda?",
  "Qual o Desenho?",
  "Qual a Serie?",
  "Quem eh o Cantor?",
  "Quem eh o Cantor?",
  "Qual eh a Musica?",
  "Qual o Desenho?",
  "Qual eh o Filme?",
  "Qual eh a Musica?",
  "Quem eh o Cantor?",
  "Qual eh o Filme?",
  "Quem eh o Cantor?",

  "Qual eh o Jogo?",
  "Qual o Programa?",
  "Quem disse isso?",
  "Qual eh o Filme?",
  "Quem eh o Filme?",
  "Qual eh a Musica?",
  "Quem eh a Cantora?",
  "Quem eh a Cantora?",
  "Qual eh a Musica?",
  "Qual eh a Serie?",
  "Quem eh o Cantor?",
  "Qual eh a Banda?",
  "Quem eh a Cantora?",
  "Quem eh a Cantora?",
  "Quem eh o Cantor?",
  "Quem disse isso?",

  "Quem eh o Cantor?",
  "Qual eh a Banda?",
  "Qual eh o Grupo?",
  "Qual eh o Filme?",
  "Qual eh a Banda?",
  "Quem Disse Isso?",
  "Qual eh a Banda?",
  "Qual eh a Banda?",
  "Qual eh a Musica?",
  "Qual o Anime?",
  "Qual eh a Novela?",
  "Qual eh a Serie?",
  "Tema de Que Filme?",
  "Quem eh a Cantora?",
  "Qual eh o Cantor?",
  "Quem Disse Isso?",

  "Qual a Banda?",
  "Quem eh o Cantor?",
  "Quem eh a Cantora?",
  "Quem eh a Cantora?",
  "Qual eh a Novela?",
  "Qual a Serie?",
  "Quem eh a Cantora?",
  "Qual a Banda?",
  "Qual eh a Novela?",
  "Tema de Que Filme?",
  "Qual eh a Novela?",
  "Qual eh a Musica?",
  "Qual o Anime?",
  "Tema de Que Filme?",
  "Qual o Anime?",
  "Hino de que Pais?"
};
